using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WeatherAPI.Models
{
    public class WeatherDefinitions
    {
      public Dictionary<string,string> DayWeatherDescription = new Dictionary<string, string>() 
      {
        { "Mostly Cloudy","wi-day-cloudy" },{ "Mostly Cloudy with Haze","wi-day-cloudy" },
        { "Mostly Cloudy and Breezy","wi-day-cloudy" },{ "Fair","wi-day-sunny" },
        { "Clear","wi-day-sunny" },{ "Fair and Breezy","wi-day-sunny" },
        { "Clear and Breezy","wi-day-sunny" },{ "Rain","wi-day-rain" },{ "Partly Sunny","wi-day-cloudy" },
        { "Heavy Rain","wi-day-rain" },{ "Rain Fog","wi-day-rain" },{ "Heavy Rain Fog","wi-day-rain" },
        { "Heavy Rain Showers Fog/Mist","wi-day-rain" },{ "Heavy Showers Rain Fog/Mist","wi-day-rain" },
        { "Haze","wi-day-haze" },{ "Fair with Haze","wi-day-haze" },{ "KeyNotFound","wi-alien" },{ "A Few Clouds","wi-cloud" },
        { "Partly Cloudy","wi-cloud" },{ "A Few Clouds with Haze","wi-cloud" },{ "Partly Cloudy with Haze","wi-cloud" },
        { "A Few Clouds and Breezy","wi-cloud" },{ "Partly Cloudy and Breezy","wi-cloud" },{ "Overcast","wi-day-sunny-overcast" },
        { "Overcast with Haze","wi-day-sunny-overcast" },{ "Overcast and Breezy","wi-day-sunny-overcast" },{ "Fog/Mist","wi-day-fog" },
        { "Fog","wi-day-fog" },{ "Freezing Fog","wi-day-fog" },{ "Shallow Fog","wi-day-fog" },{ "Partial Fog","wi-day-fog" },
        { "Patches of Fog","wi-day-fog" },{ "Fog in Vicinity","wi-day-fog" },{ "Freezing Fog in Vicinity","wi-day-fog" },
        { "Shallow Fog in Vicinity","wi-day-fog" },{ "Partial Fog in Vicinity","wi-day-fog" },{ "Patches of Fog in Vicinity","wi-day-fog" },
        { "Light Freezing Fog","wi-day-fog" },{ "Heavy Freezing Fog","wi-day-fog" },
        { "Light Rain","wi-day-showers" },{ "Rain Showers","wi-day-showers" },{ "Showers in Vicinity","wi-day-showers" },{ "Drizzle","wi-day-showers" },
        { "Light Rain Showers","wi-day-showers" },{ "Showers in Vicinity Fog/Mist","wi-day-showers" },{ "Light Drizzle","wi-day-showers" },
        { "Light Rain and Breezy","wi-day-showers" },{ "Showers in Vicinity Fog","wi-day-showers" },{ "Heavy Drizzle","wi-day-showers" },
        { "Rain Showers in Vicinity","wi-day-showers" },{ "Showers in Vicinity Haze","wi-day-showers" },{ "Light Rain Fog/Mist","wi-day-showers" },
        { "Light Showers Rain","wi-day-showers" },{ "Drizzle Fog/Mist","wi-day-showers" },{ "Showers Rain","wi-day-showers" },
        { "Light Drizzle Fog/Mist","wi-day-showers" },{ "Showers Rain in Vicinity","wi-day-showers" },{ "Heavy Drizzle Fog/Mist","wi-day-showers" },
        { "Rain Showers Fog/Mist","wi-day-showers" },{ "Light Rain Fog","wi-day-showers" },{ "Light Rain Showers Fog/Mist","wi-day-showers" },
        { "Drizzle Fog","wi-day-showers" },{ "Rain Showers in Vicinity Fog/Mist","wi-day-showers" },{ "Light Drizzle Fog","wi-day-showers" },
        { "Light Showers Rain Fog/Mist","wi-day-showers" },{ "Heavy Drizzle Fog","wi-day-showers" },{ "Showers Rain Fog/Mist","wi-day-showers" },
        { "Showers Rain in Vicinity Fog/Mist","wi-day-showers" },{ "Thunderstorm in Vicinity","wi-day-thunderstorm" },
        { "Thunderstorm in Vicinity Fog","wi-day-thunderstorm" },
        { "Thunderstorm","wi-day-thunderstorm" },{ "Thunderstorm Rain","wi-day-thunderstorm" },{ "Light Thunderstorm Rain","wi-day-thunderstorm" },
        { "Heavy Thunderstorm Rain","wi-day-thunderstorm" },
        { "Light Thunderstorm Rain Fog/Mist","wi-day-thunderstorm" },{ "Heavy Thunderstorm Rain Fog and Windy","wi-day-thunderstorm" },
        { "Heavy Thunderstorm Rain Fog/Mist","wi-day-thunderstorm" },{ "Thunderstorm Showers in Vicinity","wi-day-thunderstorm" },
        { "Light Thunderstorm Rain Haze","wi-day-thunderstorm" },{ "Heavy Thunderstorm Rain Haze","wi-day-thunderstorm" },
        { "Thunderstorm Fog","wi-day-thunderstorm" },{ "Light Thunderstorm Rain Fog","wi-day-thunderstorm" },
        { "Heavy Thunderstorm Rain Fog","wi-day-thunderstorm" },{ "Thunderstorm Light Rain","wi-day-thunderstorm" },
        { "Thunderstorm Heavy Rain","wi-day-thunderstorm" },{ "Thunderstorm Rain Fog/Mist","wi-day-thunderstorm" },
        { "Thunderstorm Light Rain Fog/Mist","wi-day-thunderstorm" },{ "Thunderstorm Heavy Rain Fog/Mist","wi-day-thunderstorm" },
        { "Thunderstorm in Vicinity Fog/Mist","wi-day-thunderstorm" },
        { "Thunderstorm in Vicinity Haze","wi-day-thunderstorm" },{ "Thunderstorm Haze in Vicinity","wi-day-thunderstorm" },
        { "Thunderstorm Light Rain Haze","wi-day-thunderstorm" },{ "Thunderstorm Heavy Rain Haze","wi-day-thunderstorm" },
        { "Thunderstorm Light Rain Fog","wi-day-thunderstorm" },
        { "Thunderstorm Heavy Rain Fog","wi-day-thunderstorm" },{ "Thunderstorm Hail","wi-day-thunderstorm" },
        { "Light Thunderstorm Rain Hail","wi-day-thunderstorm" },{ "Heavy Thunderstorm Rain Hail","wi-day-thunderstorm" },
        { "Thunderstorm Rain Hail Fog/Mist","wi-day-thunderstorm" },{ "Light Thunderstorm Rain Hail Fog/Mist","wi-day-thunderstorm" },
        { "Heavy Thunderstorm Rain Hail Fog/Hail","wi-day-thunderstorm" },{ "Thunderstorm Showers in Vicinity Hail","wi-day-thunderstorm" },
        { "Light Thunderstorm Rain Hail Haze","wi-day-thunderstorm" },{ "Heavy Thunderstorm Rain Hail Haze","wi-day-thunderstorm" },
        { "Thunderstorm Hail Fog","wi-day-thunderstorm" },{ "Light Thunderstorm Rain Hail Fog","wi-day-thunderstorm" },
        { "Heavy Thunderstorm Rain Hail Fog","wi-day-thunderstorm" },{ "Thunderstorm Light Rain Hail","wi-day-thunderstorm" },
        { "Thunderstorm Heavy Rain Hail","wi-day-thunderstorm" },
        { "Thunderstorm Light Rain Hail Fog/Mist","wi-day-thunderstorm" },{ "Thunderstorm Heavy Rain Hail Fog/Mist","wi-day-thunderstorm" },
        { "Thunderstorm in Vicinity Hail","wi-day-thunderstorm" },{ "Thunderstorm in Vicinity Hail Haze","wi-day-thunderstorm" },
        { "Thunderstorm Haze in Vicinity Hail","wi-day-thunderstorm" },{ "Thunderstorm Light Rain Hail Haze","wi-day-thunderstorm" },
        { "Thunderstorm Heavy Rain Hail Haze","wi-day-thunderstorm" },
        { "Thunderstorm Light Rain Hail Fog","wi-day-thunderstorm" },{ "Thunderstorm Heavy Rain Hail Fog","wi-day-thunderstorm" },
        { "Thunderstorm Small Hail/Snow Pellets","wi-day-thunderstorm" },{ "Thunderstorm Rain Small Hail/Snow Pellets","wi-day-thunderstorm" },
        { "Light Thunderstorm Rain Small Hail/Snow Pellets","wi-day-thunderstorm" },
        { "Heavy Thunderstorm Rain Small Hail/Snow Pellets","wi-day-thunderstorm" },{ "Ice Pellets","wi-day-hail" },
        { "Light Ice Pellets","wi-day-hail" },{ "Heavy Ice Pellets","wi-day-hail" },{ "Ice Pellets in Vicinity","wi-day-hail" },
        { "Showers Ice Pellets","wi-day-hail" },{ "Thunderstorm Ice Pellets","wi-day-hail" },{ "Ice Crystals","wi-day-hail" },{ "Hail","wi-day-hail" },
        { "Small Hail/Snow Pellets","wi-day-hail" },{ "Light Small Hail/Snow Pellets","wi-day-hail" },{ "Heavy small Hail/Snow Pellets","wi-day-hail" },
        { "Showers Hail","wi-day-hail" },{ "Hail Showers","wi-day-hail" },{ "Freezing Rain Snow","wi-day-rain-mix" },
        { "Light Freezing Rain Snow","wi-day-rain-mix" },{ "Heavy Freezing Rain Snow","wi-day-rain-mix" },{ "Freezing Drizzle Snow","wi-day-rain-mix" },
        { "Light Freezing Drizzle Snow","wi-day-rain-mix" },{ "Heavy Freezing Drizzle Snow","wi-day-rain-mix" },
        { "Snow Freezing Rain","wi-day-rain-mix" },{ "Light Snow Freezing Rain","wi-day-rain-mix" },{ "Heavy Snow Freezing Rain","wi-day-rain-mix" },
        { "Snow Freezing Drizzle","wi-day-rain-mix" },{ "Light Snow Freezing Drizzle","wi-day-rain-mix" },
        { "Heavy Snow Freezing Drizzle","wi-day-rain-mix" },{ "Rain Snow","wi-day-rain-mix" },{ "Light Rain Snow","wi-day-rain-mix" },
        { "Heavy Rain Snow","wi-day-rain-mix" },{ "Snow Rain","wi-day-rain-mix" },{ "Light Snow Rain","wi-day-rain-mix" },
        { "Heavy Snow Rain","wi-day-rain-mix" },{ "Drizzle Snow","wi-day-rain-mix" },{ "Light Drizzle Snow","wi-day-rain-mix" },
        { "Heavy Drizzle Snow","wi-day-rain-mix" },{ "Snow Drizzle","wi-day-rain-mix" },{ "Light Snow Drizzle","wi-day-rain-mix" },
        { "Rain Ice Pellets","wi-day-rain-mix" },{ "Light Rain Ice Pellets","wi-day-rain-mix" },
        { "Heavy Rain Ice Pellets","wi-day-rain-mix" },{ "Drizzle Ice Pellets","wi-day-rain-mix" },{ "Light Drizzle Ice Pellets","wi-day-rain-mix" },
        { "Heavy Drizzle Ice Pellets","wi-day-rain-mix" },{ "Ice Pellets Rain","wi-day-rain-mix" },{ "Light Ice Pellets Rain","wi-day-rain-mix" },
        { "Heavy Ice Pellets Rain","wi-day-rain-mix" },{ "Ice Pellets Drizzle","wi-day-rain-mix" },{ "Light Ice Pellets Drizzle","wi-day-rain-mix" },
        { "Heavy Ice Pellets Drizzle","wi-day-rain-mix" },{ "Freezing Rain Rain","wi-day-rain-mix" },{ "Light Freezing Rain Rain","wi-day-rain-mix" },
        { "Heavy Freezing Rain Rain","wi-day-rain-mix" },{ "Rain Freezing Rain","wi-day-rain-mix" },{ "Light Rain Freezing Rain","wi-day-rain-mix" },
        { "Heavy Rain Freezing Rain","wi-day-rain-mix" },{ "Freezing Drizzle Rain","wi-day-rain-mix" },
        { "Light Freezing Drizzle Rain","wi-day-rain-mix" },{ "Heavy Freezing Drizzle Rain","wi-day-rain-mix" },
        { "Rain Freezing Drizzle","wi-day-rain-mix" },{ "Light Rain Freezing Drizzle","wi-day-rain-mix" },
        { "Heavy Rain Freezing Drizzle","wi-day-rain-mix" },{ "Freezing Rain","wi-day-rain-mix" },{ "Freezing Drizzle","wi-day-rain-mix" },
        { "Light Freezing Rain","wi-day-rain-mix" },{ "Light Freezing Drizzle","wi-day-rain-mix" },{ "Heavy Freezing Rain","wi-day-rain-mix" },
        { "Heavy Freezing Drizzle","wi-day-rain-mix" },{ "Freezing Rain in Vicinity","wi-day-rain-mix" },
        { "Freezing Drizzle in Vicinity","wi-day-rain-mix" },{ "Snow","wi-day-snow" },{ "Light Snow","wi-day-snow" },{ "Heavy Snow","wi-day-snow" },
        { "Snow Showers","wi-day-snow" },{ "Light Snow Showers","wi-day-snow" },{ "Heavy Snow Showers","wi-day-snow" },{ "Showers Snow","wi-day-snow" },
        { "Light Showers Snow","wi-day-snow" },{ "Heavy Showers Snow","wi-day-snow" },{ "Snow Fog/Mist","wi-day-snow" },
        { "Light Snow Fog/Mist","wi-day-snow" },{ "Heavy Snow Fog/Mist","wi-day-snow" },{ "Snow Showers Fog/Mist","wi-day-snow" },
        { "Light Snow Showers Fog/Mist","wi-day-snow" },{ "Heavy Snow Showers Fog/Mist","wi-day-snow" },{ "Showers Snow Fog/Mist","wi-day-snow" },
        { "Light Showers Snow Fog/Mist","wi-day-snow" },{ "Heavy Showers Snow Fog/Mist","wi-day-snow" },{ "Snow Fog","wi-day-snow" },
        { "Light Snow Fog","wi-day-snow" },{ "Heavy Snow Fog","wi-day-snow" },{ "Snow Showers Fog","wi-day-snow" },
        { "Light Snow Showers Fog","wi-day-snow" },{ "Heavy Snow Showers Fog","wi-day-snow" },{ "Showers Snow Fog","wi-day-snow" },
        { "Light Showers Snow Fog","wi-day-snow" },{ "Heavy Showers Snow Fog","wi-day-snow" },{ "Showers in Vicinity Snow","wi-day-snow" },
        { "Snow Showers in Vicinity","wi-day-snow" },{ "Snow Showers in Vicinity Fog/Mist","wi-day-snow" },
        { "Snow Showers in Vicinity Fog","wi-day-snow" },{ "Low Drifting Snow","wi-day-snow" },{ "Blowing Snow","wi-day-snow" },
        { "Snow Low Drifting Snow","wi-day-snow" },{ "Snow Blowing Snow","wi-day-snow" },{ "Light Snow Low Drifting Snow","wi-day-snow" },
        { "Light Snow Blowing Snow","wi-day-snow" },{ "Light Snow Blowing Snow Fog/Mist","wi-day-snow" },
        { "Heavy Snow Low Drifting Snow","wi-day-snow" },{ "Heavy Snow Blowing Snow","wi-day-snow" },{ "Thunderstorm Snow","wi-day-snow" },
        { "Light Thunderstorm Snow","wi-day-snow" },{ "Heavy Thunderstorm Snow","wi-day-snow" },{ "Snow Grains","wi-day-snow" },
        { "Light Snow Grains","wi-day-snow" },{ "Heavy Snow Grains","wi-day-snow" },{ "Heavy Blowing Snow","wi-day-snow" },
        { "Blowing Snow in Vicinity","wi-day-snow" },{ "Windy","wi-windy" },{ "Breezy","wi-windy" },{ "Fair and Windy","wi-windy" },
        { "A Few Clouds and Windy","wi-windy" },{ "Partly Cloudy and Windy","wi-windy" },{ "Mostly Cloudy and Windy","wi-windy" },
        { "Overcast and Windy","wi-windy" }
      };
      public Dictionary<string,string> NightWeatherDescription = new Dictionary<string, string>() 
      {
          { "Mostly Cloudy","wi-night-cloudy" },{ "Mostly Cloudy with Haze","wi-night-cloudy" },{ "Mostly Cloudy and Breezy","wi-night-cloudy" },
          { "Fair","wi-night-clear" },{ "Clear","wi-night-clear" },{ "Fair and Breezy","wi-night-clear" },{ "Clear and Breezy","wi-night-clear" },
          { "Rain","wi-night-rain" },{ "Heavy Rain","wi-night-rain" },{ "Rain Fog","wi-night-rain" },{ "Heavy Rain Fog","wi-night-rain" },
          { "Heavy Rain Showers Fog/Mist","wi-night-rain" },{ "Heavy Showers Rain Fog/Mist","wi-night-rain" },{ "Haze","wi-day-haze" },
          { "Fair with Haze","wi-day-haze" },{ "KeyNotFound","wi-alien" },{ "A Few Clouds","wi-cloud" },{ "Partly Cloudy","wi-cloud" },
          { "A Few Clouds with Haze","wi-cloud" },{ "Partly Cloudy with Haze","wi-cloud" },{ "A Few Clouds and Breezy","wi-cloud" },
          { "Partly Cloudy and Breezy","wi-cloud" },{ "Overcast","wi-day-sunny-overcast" },{ "Overcast with Haze","wi-day-sunny-overcast" },
          { "Overcast and Breezy","wi-day-sunny-overcast" },{ "Fog/Mist","wi-night-fog" },{ "Fog","wi-night-fog" },{ "Freezing Fog","wi-night-fog" },
          { "Shallow Fog","wi-night-fog" },{ "Partial Fog","wi-night-fog" },{ "Patches of Fog","wi-night-fog" },{ "Fog in Vicinity","wi-night-fog" },
          { "Freezing Fog in Vicinity","wi-night-fog" },{ "Shallow Fog in Vicinity","wi-night-fog" },{ "Partial Fog in Vicinity","wi-night-fog" },
          { "Patches of Fog in Vicinity","wi-night-fog" },{ "Light Freezing Fog","wi-night-fog" },
          { "Heavy Freezing Fog","wi-night-fog" },{ "Light Rain","wi-night-showers" },{ "Rain Showers","wi-night-showers" },
          { "Showers in Vicinity","wi-night-showers" },{ "Drizzle","wi-night-showers" },{ "Light Rain Showers","wi-night-showers" },
          { "Showers in Vicinity Fog/Mist","wi-night-showers" },{ "Light Drizzle","wi-night-showers" },{ "Light Rain and Breezy","wi-night-showers" },
          { "Showers in Vicinity Fog","wi-night-showers" },{ "Heavy Drizzle","wi-night-showers" },{ "Rain Showers in Vicinity","wi-night-showers" },
          { "Showers in Vicinity Haze","wi-night-showers" },{ "Light Rain Fog/Mist","wi-night-showers" },{ "Light Showers Rain","wi-night-showers" },
          { "Drizzle Fog/Mist","wi-night-showers" },{ "Showers Rain","wi-night-showers" },{ "Light Drizzle Fog/Mist","wi-night-showers" },
          { "Showers Rain in Vicinity","wi-night-showers" },{ "Heavy Drizzle Fog/Mist","wi-night-showers" },
          { "Rain Showers Fog/Mist","wi-night-showers" },{ "Light Rain Fog","wi-night-showers" },{ "Light Rain Showers Fog/Mist","wi-night-showers" },
          { "Drizzle Fog","wi-night-showers" },{ "Rain Showers in Vicinity Fog/Mist","wi-night-showers" },{ "Light Drizzle Fog","wi-night-showers" },
          { "Light Showers Rain Fog/Mist","wi-night-showers" },{ "Heavy Drizzle Fog","wi-night-showers" },{ "Showers Rain Fog/Mist","wi-night-showers" },
          { "Showers Rain in Vicinity Fog/Mist","wi-night-showers" },{ "Thunderstorm in Vicinity","wi-night-thunderstorm" },
          { "Thunderstorm in Vicinity Fog","wi-night-thunderstorm" },
          { "Thunderstorm","wi-night-thunderstorm" },{ "Thunderstorm Rain","wi-night-thunderstorm" },{ "Light Thunderstorm Rain","wi-night-thunderstorm" },
          { "Heavy Thunderstorm Rain","wi-night-thunderstorm" },
          { "Light Thunderstorm Rain Fog/Mist","wi-night-thunderstorm" },{ "Heavy Thunderstorm Rain Fog and Windy","wi-night-thunderstorm" },
          { "Heavy Thunderstorm Rain Fog/Mist","wi-night-thunderstorm" },
          { "Light Thunderstorm Rain Haze","wi-night-thunderstorm" },{ "Heavy Thunderstorm Rain Haze","wi-night-thunderstorm" },
          { "Light Thunderstorm Rain Fog","wi-night-thunderstorm" },
          { "Heavy Thunderstorm Rain Fog","wi-night-thunderstorm" },{ "Thunderstorm Light Rain","wi-night-thunderstorm" },
          { "Thunderstorm Heavy Rain","wi-night-thunderstorm" },{ "Thunderstorm Rain Fog/Mist","wi-night-thunderstorm" },
          { "Thunderstorm Light Rain Fog/Mist","wi-night-thunderstorm" },{ "Thunderstorm Heavy Rain Fog/Mist","wi-night-thunderstorm" },
          { "Thunderstorm in Vicinity Fog/Mist","wi-night-thunderstorm" },{ "Thunderstorm Showers in Vicinity","wi-night-thunderstorm" },
          { "Thunderstorm in Vicinity Haze","wi-night-thunderstorm" },{ "Thunderstorm Haze in Vicinity","wi-night-thunderstorm" },
          { "Thunderstorm Light Rain Haze","wi-night-thunderstorm" },{ "Thunderstorm Heavy Rain Haze","wi-night-thunderstorm" },
          { "Thunderstorm Fog","wi-night-thunderstorm" },{ "Thunderstorm Light Rain Fog","wi-night-thunderstorm" },
          { "Thunderstorm Heavy Rain Fog","wi-night-thunderstorm" },{ "Thunderstorm Hail","wi-night-thunderstorm" },
          { "Light Thunderstorm Rain Hail","wi-night-thunderstorm" },{ "Heavy Thunderstorm Rain Hail","wi-night-thunderstorm" },
          { "Thunderstorm Rain Hail Fog/Mist","wi-night-thunderstorm" },{ "Light Thunderstorm Rain Hail Fog/Mist","wi-night-thunderstorm" },
          { "Heavy Thunderstorm Rain Hail Fog/Hail","wi-night-thunderstorm" },{ "Thunderstorm Showers in Vicinity Hail","wi-night-thunderstorm" },
          { "Light Thunderstorm Rain Hail Haze","wi-night-thunderstorm" },{ "Heavy Thunderstorm Rain Hail Haze","wi-night-thunderstorm" },
          { "Thunderstorm Hail Fog","wi-night-thunderstorm" },{ "Light Thunderstorm Rain Hail Fog","wi-night-thunderstorm" },
          { "Heavy Thunderstorm Rain Hail Fog","wi-night-thunderstorm" },{ "Thunderstorm Light Rain Hail","wi-night-thunderstorm" },
          { "Thunderstorm Heavy Rain Hail","wi-night-thunderstorm" },
          { "Thunderstorm Light Rain Hail Fog/Mist","wi-night-thunderstorm" },{ "Thunderstorm Heavy Rain Hail Fog/Mist","wi-night-thunderstorm" },
          { "Thunderstorm in Vicinity Hail","wi-night-thunderstorm" },{ "Thunderstorm in Vicinity Hail Haze","wi-night-thunderstorm" },
          { "Thunderstorm Haze in Vicinity Hail","wi-night-thunderstorm" },{ "Thunderstorm Light Rain Hail Haze","wi-night-thunderstorm" },
          { "Thunderstorm Heavy Rain Hail Haze","wi-night-thunderstorm" },
          { "Thunderstorm Light Rain Hail Fog","wi-night-thunderstorm" },{ "Thunderstorm Heavy Rain Hail Fog","wi-night-thunderstorm" },
          { "Thunderstorm Small Hail/Snow Pellets","wi-night-thunderstorm" },{ "Thunderstorm Rain Small Hail/Snow Pellets","wi-night-thunderstorm" },
          { "Light Thunderstorm Rain Small Hail/Snow Pellets","wi-night-thunderstorm" },
          { "Heavy Thunderstorm Rain Small Hail/Snow Pellets","wi-night-thunderstorm" },{ "Ice Pellets","wi-night-hail" },
          { "Light Ice Pellets","wi-night-hail" },{ "Heavy Ice Pellets","wi-night-hail" },{ "Ice Pellets in Vicinity","wi-night-hail" },
          { "Showers Ice Pellets","wi-night-hail" },{ "Thunderstorm Ice Pellets","wi-night-hail" },{ "Ice Crystals","wi-night-hail" },
          { "Hail","wi-night-hail" },{ "Small Hail/Snow Pellets","wi-night-hail" },{ "Light Small Hail/Snow Pellets","wi-night-hail" },
          { "Heavy small Hail/Snow Pellets","wi-night-hail" },{ "Showers Hail","wi-night-hail" },{ "Hail Showers","wi-night-hail" },
          { "Freezing Rain Snow","wi-night-rain-mix" },{ "Light Freezing Rain Snow","wi-night-rain-mix" },
          { "Heavy Freezing Rain Snow","wi-night-rain-mix" },{ "Freezing Drizzle Snow","wi-night-rain-mix" },
          { "Light Freezing Drizzle Snow","wi-night-rain-mix" },{ "Heavy Freezing Drizzle Snow","wi-night-rain-mix" },
          { "Snow Freezing Rain","wi-night-rain-mix" },{ "Light Snow Freezing Rain","wi-night-rain-mix" },
          { "Heavy Snow Freezing Rain","wi-night-rain-mix" },{ "Snow Freezing Drizzle","wi-night-rain-mix" },
          { "Light Snow Freezing Drizzle","wi-night-rain-mix" },{ "Heavy Snow Freezing Drizzle","wi-night-rain-mix" },
          { "Rain Snow","wi-night-rain-mix" },{ "Light Rain Snow","wi-night-rain-mix" },{ "Heavy Rain Snow","wi-night-rain-mix" },
          { "Snow Rain","wi-night-rain-mix" },{ "Light Snow Rain","wi-night-rain-mix" },{ "Heavy Snow Rain","wi-night-rain-mix" },
          { "Drizzle Snow","wi-night-rain-mix" },{ "Light Drizzle Snow","wi-night-rain-mix" },{ "Heavy Drizzle Snow","wi-night-rain-mix" },
          { "Snow Drizzle","wi-night-rain-mix" },{ "Light Snow Drizzle","wi-night-rain-mix" },
          { "Rain Ice Pellets","wi-night-rain-mix" },{ "Light Rain Ice Pellets","wi-night-rain-mix" },{ "Heavy Rain Ice Pellets","wi-night-rain-mix" },
          { "Drizzle Ice Pellets","wi-night-rain-mix" },{ "Light Drizzle Ice Pellets","wi-night-rain-mix" },
          { "Heavy Drizzle Ice Pellets","wi-night-rain-mix" },{ "Ice Pellets Rain","wi-night-rain-mix" },
          { "Light Ice Pellets Rain","wi-night-rain-mix" },{ "Heavy Ice Pellets Rain","wi-night-rain-mix" },
          { "Ice Pellets Drizzle","wi-night-rain-mix" },{ "Light Ice Pellets Drizzle","wi-night-rain-mix" },
          { "Heavy Ice Pellets Drizzle","wi-night-rain-mix" },{ "Freezing Rain Rain","wi-night-rain-mix" },
          { "Light Freezing Rain Rain","wi-night-rain-mix" },{ "Heavy Freezing Rain Rain","wi-night-rain-mix" },
          { "Rain Freezing Rain","wi-night-rain-mix" },{ "Light Rain Freezing Rain","wi-night-rain-mix" },
          { "Heavy Rain Freezing Rain","wi-night-rain-mix" },{ "Freezing Drizzle Rain","wi-night-rain-mix" },
          { "Light Freezing Drizzle Rain","wi-night-rain-mix" },{ "Heavy Freezing Drizzle Rain","wi-night-rain-mix" },
          { "Rain Freezing Drizzle","wi-night-rain-mix" },{ "Light Rain Freezing Drizzle","wi-night-rain-mix" },
          { "Heavy Rain Freezing Drizzle","wi-night-rain-mix" },{ "Freezing Rain","wi-night-rain-mix" },{ "Freezing Drizzle","wi-night-rain-mix" },
          { "Light Freezing Rain","wi-night-rain-mix" },{ "Light Freezing Drizzle","wi-night-rain-mix" },{ "Heavy Freezing Rain","wi-night-rain-mix" },
          { "Heavy Freezing Drizzle","wi-night-rain-mix" },{ "Freezing Rain in Vicinity","wi-night-rain-mix" },
          { "Freezing Drizzle in Vicinity","wi-night-rain-mix" },{ "Snow","wi-night-snow" },{ "Light Snow","wi-night-snow" },
          { "Heavy Snow","wi-night-snow" },{ "Snow Showers","wi-night-snow" },{ "Light Snow Showers","wi-night-snow" },
          { "Heavy Snow Showers","wi-night-snow" },{ "Showers Snow","wi-night-snow" },{ "Light Showers Snow","wi-night-snow" },
          { "Heavy Showers Snow","wi-night-snow" },{ "Snow Fog/Mist","wi-night-snow" },{ "Light Snow Fog/Mist","wi-night-snow" },
          { "Heavy Snow Fog/Mist","wi-night-snow" },{ "Snow Showers Fog/Mist","wi-night-snow" },{ "Light Snow Showers Fog/Mist","wi-night-snow" },
          { "Heavy Snow Showers Fog/Mist","wi-night-snow" },{ "Showers Snow Fog/Mist","wi-night-snow" },{ "Light Showers Snow Fog/Mist","wi-night-snow" },
          { "Heavy Showers Snow Fog/Mist","wi-night-snow" },{ "Snow Fog","wi-night-snow" },{ "Light Snow Fog","wi-night-snow" },
          { "Heavy Snow Fog","wi-night-snow" },{ "Snow Showers Fog","wi-night-snow" },{ "Light Snow Showers Fog","wi-night-snow" },
          { "Heavy Snow Showers Fog","wi-night-snow" },{ "Showers Snow Fog","wi-night-snow" },{ "Light Showers Snow Fog","wi-night-snow" },
          { "Heavy Showers Snow Fog","wi-night-snow" },{ "Showers in Vicinity Snow","wi-night-snow" },{ "Snow Showers in Vicinity","wi-night-snow" },
          { "Snow Showers in Vicinity Fog/Mist","wi-night-snow" },{ "Snow Showers in Vicinity Fog","wi-night-snow" },
          { "Low Drifting Snow","wi-night-snow" },{ "Blowing Snow","wi-night-snow" },{ "Snow Low Drifting Snow","wi-night-snow" },
          { "Snow Blowing Snow","wi-night-snow" },{ "Light Snow Low Drifting Snow","wi-night-snow" },{ "Light Snow Blowing Snow","wi-night-snow" },
          { "Light Snow Blowing Snow Fog/Mist","wi-night-snow" },{ "Heavy Snow Low Drifting Snow","wi-night-snow" },
          { "Heavy Snow Blowing Snow","wi-night-snow" },{ "Thunderstorm Snow","wi-night-snow" },{ "Light Thunderstorm Snow","wi-night-snow" },
          { "Heavy Thunderstorm Snow","wi-night-snow" },{ "Snow Grains","wi-night-snow" },{ "Light Snow Grains","wi-night-snow" },
          { "Heavy Snow Grains","wi-night-snow" },{ "Heavy Blowing Snow","wi-night-snow" },{ "Blowing Snow in Vicinity","wi-night-snow" },
          { "Windy","wi-windy" },{ "Breezy","wi-windy" },{ "Fair and Windy","wi-windy" },{ "A Few Clouds and Windy","wi-windy" },
          { "Partly Cloudy and Windy","wi-windy" },{ "Mostly Cloudy and Windy","wi-windy" },{ "Overcast and Windy","wi-windy" }
      };
    } 
    
}
